export const placeholder = {
  readingtime: "",
  title: "",
  description: "",
  url: "",
  image: "",
  author: "Justin Schmitz",
  data_published: "22.10.20",
  date_modified: "22.10.20",
  sources: [""],
  tags: [""],
  questions: [""],
};

export const index = {
  description:
    "Convert all image types to AVIF for free.🚀 Supports bulk converting. Blazing fast. Privacy protected. Compress your images now!⏱",
  url: "",
  image: "",
  author: "Justin Schmitz",
  data_published: "01.09.20",
  date_modified: "10.01.21",
};

export const blog = {
  description:
    "Get smarter. Read a lot of articles about AVIF and images on the web. Right here, right now.",
  url: "blog/",
  image: "",
  author: "Justin Schmitz",
  data_published: "01.09.20",
  date_modified: "10.01.21",
};

export const tutorials = {
  description:
    "Get smarter. Read a lot of articles about AVIF and images on the web. Right here, right now.",
  url: "blog/tutorials/",
  image: "",
  author: "Justin Schmitz",
  data_published: "01.09.20",
  date_modified: "10.01.21",
};

export const privacyPolicy = {
  title: "Privacy Policy",
  description: "Learn how we utilize your data to optimize our service.",
  url: "privacy-policy/",
  image: "",
  author: "Justin Schmitz",
  data_published: "01.09.20",
  date_modified: "10.01.21",
};

export const useAvifInCloudflare = {
  description:
    "Cloudflare has added support for AVIF, a new image format. Learn how to optimize images and convert them to WebP or AVIF on demand.",
  title: "Do you benefit from Cloudwork's AVIF support?",
  url: "blog/tutorials/use-avif-in-cloudflare",
  image: "",
  author: "Justin Schmitz",
  data_published: "01.10.20",
  date_modified: "01.10.20",
  sources: [
    "blog.cloudflare.com/generate-avif-images-with-image-resizing",
    "blog.cloudflare.com/http3-the-past-present-and-future",
    "cloudflare.com/case-studies/discord",
    "cloudflare.com/case-studies/hubspot",
    "cloudflare.com/case-studies/zendesk",
    "cloudflare.com/plans/",
    "developers.cloudflare.com/images",
    "developers.cloudflare.com/images/resizing-with-workers",
    "endler.dev/2020/perf",
    "ilovepdf.com/help/privacy",
    "meterpreter.org/cloudflare-supports-the-new-avif-image-format-in-image-resizing",
    "neowin.net/news/cloudflare-image-resizing-adds-support-for-avif-images",
    "w3techs.com/technologies/details/cn-cloudflare",
  ],
  tags: [
    "image format",
    "cloudflare",
    "browser",
    "image resizing",
    "google",
    "file size",
    "safari",
    "apple",
    "bandwidth",
    "header",
    "video codec",
    "sites",
    "event",
    "request header",
    "jpeg xr",
    "image compression",
    "webp support",
    "cloudflare workers",
    "original image",
    "use case",
  ],
  questions: [
    "Cloudflare supports the new AVIF image format in Image Resizing",
    "Progressively delivering new image formats with CSS and Cloudflare Workers",
    "Cloudflare Image Resizing adds support for AVIF images",
    "Cloudflare Workers and AVIF Support",
    "Cloudflare Image Resizing docs",
    "AVIF, a next-gen image format for the web",
    "Resizing with Cloudflare Workers",
  ],
  readingtime: "8",
};

export const useAvifInCss = {
  readingtime: "8",
  title: "Fully support AVIF in your CSS today.",
  description:
    "Learn how to boost your website by easily implementing the new AVIF image format in the `background-images` of your CSS.",
  url: "blog/tutorials/use-avif-in-css",
  image: "",
  author: "Justin Schmitz",
  data_published: "01.10.20",
  date_modified: "01.10.20",
  sources: [
    "caniuse.com/css-image-set",
    "caniuse.com/avif ",
    "drafts.csswg.org/css-images-4",
    "dev.to/nucliweb/detect-avif-image-support-to-use-in-your-css-4pen",
    "dev.to/nucliweb/detect-avif-image-support-to-use-in-your-css-4pen",
    "ghacks.net/2021/01/10/firefox-86-avif-support-enabled-by-default/",
    "github.com/djpogo/avif-webp-css-support",
    "omgubuntu.co.uk/2021/01/firefox-86-avif-image-support",
    "raoulkramer.de/avif-and-webp-images-as-css-background-images",
  ],
  tags: [
    "image format",
    "squoosh",
    "firefox",
    "javascript",
    "files",
    "avif format",
    "users",
    "original image",
    "decoders",
    "devices",
    "google",
    "bytes",
    "user experience",
    "css background",
    "github",
    "background images",
    "file size",
    "people",
    "file format",
  ],
  questions: [
    "What is AVIF image format",
    "Is AVIF lossless",
    "Which image format can be displayed by all Web browsers",
    "What is a Web image",
    "How do I use an AVIF file",
    "Which image format is highest quality",
    "Progressively delivering new image formats with CSS",
    "My Blog Just Got Faster: AVIF Support",
    "PostCSS plugin to use AVIF in CSS background",
    "avif and webp images as css background images",
    "Delivering New Image Formats",
    "css background-image usage of avif and webp",
  ],
};

export const useAvifInEdge = {
  readingtime: "5",
  title: "View AVIF Images In Microsoft Edge",
  description:
    "Internet Explorer 6, the latest brow.. oh, it's called Edge? Well, okay. The current state about AVIF in Edge is difficult. Learn more about it here.",
  url: "blog/tutorials/use-avif-in-edge",
  image: "",
  author: "Justin Schmitz",
  data_published: "07.10.20",
  date_modified: "07.10.20",
  sources: [
    "en.wikipedia.org/wiki/AV1",
    "microsoft.com/en-us/p/av1-video-extension/9mvzqvxjbq9v",
    "support.microsoft.com/en-us/microsoft-edge",
    "techcommunity.microsoft.com/t5/discussions/avif-image-support/m-p/1802087",
    "thewindowsclub.com/what-is-avif-or-av1",
    "zdnet.de/88384405/microsoft-kuendigt-hardwarebeschleunigung-fuer-av1-an",
  ],
  tags: [
    "windows 10",
    "image format",
    "avif images",
    "google",
    "av1 video",
    "users",
    "enable",
    "firefox",
    "av1 video extension",
    "video extension",
    "alliance",
    "alliance for open media",
    "browser",
    "file explorer",
    "file format",
    "image file",
    "image file format",
    "av1 image",
    "video codec",
    "google chrome",
  ],
  questions: [
    "Windows 10 graphics: GPU-powered AV1 video compression coming soon, says Microsoft",
    "To Enable AVIF image format support in Firefox",
    "Windows 10 will support AVIF images format",
    "To Enable AVIF Support in Microsoft Edge,",
    "Enable AVIF Support in Edge",
    "Enable AVIF or AV1 support in Chrome, Edge and Firefox",
    "What is AVIF or AV1? How to enable its support in Chrome and Firefox?",
    "What is AVIF or AV1 image format",
    "Windows 10 AVIF Support Gone?",
  ],
};

export const useAvifInFirefox = {
  readingtime: "8",
  title: "The Complete Guide about AVIF in Firefox for 2021",
  description:
    "Yes, you can! Learn how to activate AVIF support for Firefox with a simple tutorial.",
  url: "blog/tutorials/use-avif-in-edge",
  image: "",
  author: "Justin Schmitz",
  data_published: "14.10.20",
  date_modified: "14.10.20",
  sources: [
    "bugzilla.mozilla.org/buglist.cgi?short_desc_type=allwordssubstr&query_format=advanced&short_desc=AVIF",
    "bugzilla.mozilla.org/show_bug.cgi?id=1443863",
    "bugzilla.mozilla.org/show_bug.cgi?id=1625363",
    "caniuse.com/?search=image%20format",
    "caniuse.com/avif",
    "ghacks.net/2020/05/04/mozilla-implements-experimental-avif-image-support-in-firefox-nightly",
    "groups.google.com/g/mozilla.dev.platform/c/bIM8ZaFS-d8/m/VwbG7okoCwAJ?pli=1",
    "groups.google.com/g/mozilla.dev.platform/c/vPby-nEugJY/m/md23-8UiCQAJ?pli=1",
    "itmagazine.ch/artikel/72550/Firefox_und_Chrome_demnaechst_mit_AVIF-Support",
    "libre-software.net/avif-test",
    "linuxnews.de/2020/06/firefox-77-mit-neuem-netflix-bildformat",
    "meterpreter.org/firefox-will-soon-enable-support-for-avif-image-by-default",
    "phoronix.com/scan.php?page=news_item&px=Firefox-Nearly-Ready-AVIF",
    "reddit.com/r/AV1/comments/khmuxs/mozilla_firefox_appears_ready_to_enable_avif",
    "reddit.com/r/firefox/comments/gegafv/psa_firefox_77_beta_includes_avif_the_av1_image",
    "reddit.com/r/firefox/comments/jprgdx/will_firefox_be_able_to_fully_support_avif_format",
    "wiki.mozilla.org/BMO/UserGuide/BugFields#dependson",
    "wiki.mozilla.org/Release_Management/Calendar",
    "zdnet.com/article/chrome-and-firefox-are-getting-support-for-the-new-avif-image-format",
  ],
  tags: [
    "avif image",
    "browser",
    "mozilla",
    "firefox",
    "Mozilla firefox",
    "file format",
    "image format",
    "image file",
    "image file format",
    "open source",
    "video format",
    "avif files",
  ],
  questions: [
    "PSA: Firefox 77 Beta includes AVIF (the AV1 Image File Format) support",
    "Chrome and Firefox are getting support for the new AVIF image format",
    "Mozilla implements experimental AVIF image support in Firefox Nightly",
    "AVIF image format",
    "Firefox will soon enable support for AVIF image by default",
    "Support coming to browsers",
    "Is your browser capable of displaying AVIF images?",
    "Which browsers are capable of displaying AVIF pictures?",
    "How to convert images to the AVIF file format",
    "Will Firefox be able to fully support AVIF format?",
    "How do I open an AVIF file",
    "What is AVIF image format",
    "Is AVIF lossless",
    "What is a Web image",
  ],
};

export const useAvifInFrameworks = {
  readingtime: "5",
  title: "Use AVIF in Frameworks like Vue, React & Angular",
  description: "Serving AVIF images via JavaScript frameworks is quite easy - find out more here.",
  url: "blog/tutorials/use-avif-in-frameworks",
  image: "",
  author: "Justin Schmitz",
  data_published: "21.10.20",
  date_modified: "21.10.20",
  sources: [
    "github.com/angular/angular-cli/releases?after=v11.0.2",
    "github.com/facebook/create-react-app/pull/9611",
    "image.nuxtjs.org/nuxt-picture",
    "newreleases.io/project/github/angular/angular-cli/release/v11.0.0-rc.1",
    "nuxtjs.org/docs/release-notes",
    "stackoverflow.com/questions/59433854/how-do-i-use-avif-images-in-react-single-page-web-app",
    "webpack.js.org/loaders/file-loader",
  ],
  tags: [
    "avif",
    "image optimization",
    "javascript",
    "framework",
    "angular",
    "svelte",
    "react",
    "vue",
    "nuxt",
    "gatbsy",
    "meteor",
    "backbone",
    "polymer",
    "ember",
    "javascript framework",
  ],
  questions: ["How do I use AVIF images in React Single page Web App"],
};

export const useAvifInGimp = {
  readingtime: "5",
  title: "Discover the basics of AVIF in GIMP",
  description:
    "GIMP 2.10.22 now includes HEIC support and AVIF support. Learn how to take advantage of these new features.",
  url: "blog/tutorials/use-avif-in-gimp/",
  image: "",
  author: "Justin Schmitz",
  data_published: "28.10.20",
  date_modified: "28.10.20",
  sources: [
    "gimp.org/news/2020/10/07/gimp-2-10-22-released",
    "github.com/novomesk/gimp-avif-plugin",
    "gitlab.gnome.org/GNOME/gimp/-/issues/2668",
    "linuxreviews.org/GIMP_2.10.22_Is_Released_With_AVIF_Support_And_Improved_Support_For_Many_Other_File_Formats",
    "phoronix.com/scan.php?page=news_item&px=GIMP-2.10.22-Released",
  ],
  tags: [
    "linux",
    "avif support",
    "file format",
    "feature",
    "plug in",
    "developer",
    "firefox",
    "image editor",
    "image file format",
    "image format",
    "color profiles",
    "avif files",
    "macos",
    "flatpak",
    "flathub",
    "bug fixes",
    "avif images",
    "paint shop pro",
    "image bounds",
    "16 bit integer",
  ],
  questions: [
    "GIMP 2.10.22 Is Released With AVIF Support And Improved Support For Many Other File Formats",
    "Download Now: GIMP 2.10.22 Released with Major File Format Improvements",
    "GIMP 2.10.22 Released with Major File Format Improvements",
    "Add .avif (AV1 Image File Format) support to GIMP",
    "GIMP 2.10.22 Released with AVIF Support, Improved PSP and TIFF Support",
    "What is AVIF? How to Use AV1 Image Format Images in GIMP",
    "How to Start Using AVIF Images in GIMP",
  ],
};

export const useAvifInHtml = {
  readingtime: "8",
  title: "How to get started with AVIF using HTML",
  description:
    "Enjoy this in-depth guide on how to use AVIF in HTML. Featuring examples with modern delivery standards.",
  url: "blog/tutorials/use-avif-in-html",
  image: "",
  author: "Justin Schmitz",
  data_published: "04.11.20",
  date_modified: "04.11.20",
  sources: [
    "aomedia.org/about",
    "aomedia.org/av1-features/get-started",
    "caniuse.com/picture",
    "caniuse.com/avif",
    "caniuse.com/loading-lazy-attr",
    "caniuse.com/webp",
    "css-tricks.com/avif-has-landed",
    "developer.apple.com/documentation/safari-release-notes/safari-14-release-notes",
    "industrialempathy.com/posts/image-optimizations/",
    "tollwerk.de/blog/schlanke-responsive-bilder-mit-picture-mozjpeg-webp-avif-sqip",
    "mediaevent.de/bilddatenformate-jpg-avif-png-webp",
  ],
  tags: [
    "files",
    "image avif",
    "img src",
    "image format",
    "avif support",
    "image webp",
    "sizes",
    "firefox",
    "avif images",
    "webp image",
    "file size",
    "avif files",
    "github",
    "google",
    "file format",
    "google chrome",
    "image file",
    "picture",
  ],
  questions: [
    "AVIF Image Format – The Next-Gen Compression Codec",
    "Future Of AVIF: Browser Compatibility for Chrome and Firefox",
    "File sizes: AVIF vs WebP vs PNG/JPEG",
    "A More Optimal Image Format",
    "A way to leverage new image formats",
    "How to Create AVIF Files?",
    "Is AVIF worth an investment from you as a developer/company? Ready for prime time?",
    "What I decided about image formats",
    "What is AV Image Format (AVIF)",
    "How to Use AVIF: The New Next-Gen Image Compression Format",
    "Is your browser capable of displaying AVIF images?",
    "How to convert images to the AVIF file format",
    "How to create AVIF images",
    "What is 'acceptable quality'?",
  ],
};

export const useAvifInNextjs = {
  readingtime: "6",
  title: "Start using AVIF in your Next.JS project",
  description:
    "Curious to read on how to use AVIF images in Next.JS? Well, this site does exactly that! Learn more.",
  url: "blog/tutorials/use-avif-in-nextjs",
  image: "",
  author: "Justin Schmitz",
  data_published: "11.11.20",
  date_modified: "11.11.20",
  sources: [
    "github.com/cyrilwanner/next-optimized-images",
    "github.com/twopluszero/next-images",
    "github.com/vercel/next.js/discussions/17141",
    "github.com/vercel/next.js/tree/canary/examples/image-component",
    "nextjs.org/docs/basic-features/image-optimization",
  ],
  tags: [
    "avif",
    "react",
    "nextjs",
    "next.js",
    "next js",
    "google",
    "webpack",
    "const",
    "developer",
    "javascript",
    "user experience",
    "image component",
    "files",
    "export default",
    "react dom",
    "react components",
    "code splitting",
    "server side rendering",
    "server side",
    "image optimization",
    "format",
  ],
  questions: [
    "Automatic Image Optimization: Next.js 10 New Standards for 2020",
    "Server-side rendering with Gatsby and Next.js",
    "Automatic Image Optimization",
    "What are the advantages of using, for instance, Next.js over Gatsby, in that case?",
    "How Gatsby and Next.js really work (and what it means for speed and SEO)",
  ],
};

export const useAvifInWindows = {
  readingtime: "6",
  title: "Does Windows support AVIF already?",
  description:
    "Learn how to make AVIF images load on native Windows 10 applications such as Paint and File Explorer.",
  url: "blog/tutorials/use-avif-in-windows/",
  image: "",
  author: "Justin Schmitz",
  data_published: "18.11.20",
  date_modified: "18.11.20",
  sources: [
    "zdnet.com/article/chrome-and-firefox-are-getting-support-for-the-new-avif-image-format",
    "techzdudes.com/new-avif-image-format-support-is-coming-soon-to-chrome-and-firefox",
    "windowslatest.com/2018/12/27/file-explorer-and-paint-to-get-support-for-avif-images-in-windows-10",
    "takesontech.com/newest-windows-10-insider-build-adds-av1-avif-format-support",
    "winaero.com/avif-format-support-comes-to-windows-10-version-1903",
    "ghacks.net/2018/12/28/windows-10-1903-to-support-avif-format",
    "mspoweruser.com/windows-file-explorer-and-microsoft-paint-will-soon-support-avif-images",
    "fossbytes.com/windows-10-file-explorer-and-paint-support-avif-image-format",
    "meterpreter.org/windows-10-will-support-avif-images-format",
    "minitool.com/news/file-explorer-microsoft-paint-support-avif-images",
    "winbuzzer.com/2018/12/27/microsoft-brings-avif-support-to-windows-10-through-file-explorer-and-paint-xcxwbn",
    "howto-connect.com/windows-10-1903-version-support-avif-file-type",
    "techdows.com/2020/08/chrome-85-to-support-avif-image-format",
    "onmsft.com/news/latest-windows-insider-build-adds-avif-image-format-support",
    "bleepingcomputer.com/news/microsoft/microsoft-is-adding-avif-image-support-to-windows-10",
  ],
  tags: [
    "windows 10",
    "file explorer",
    "explorer",
    "paint",
    "av1 video",
    "avif images",
    "image format",
    "video extension",
    "av1 video extension",
    "avif thumbnails",
    "file format",
    "windows file explorer",
    "image file format",
    "alliance for open media",
    "image file",
    "windows insider",
    "mspaint exe",
    "display exif metadata",
    "preview release",
    "insider program",
  ],
  questions: [
    "How do I play av1 videos",
    "Who uses av1 codec",
    "Is av1 royalty free",
    "Microsoft Brings AVIF Support to Windows 10 Through File Explorer and Paint",
    "Windows 10 File Explorer And Paint Will Now Support AVIF Image Format",
    "File Explorer and Paint to get support for AVIF images in Windows 10",
    "Windows File Explorer and Microsoft Paint will soon support AVIF images",
    "Windows 10 1903 Version Support for AVIF File Type (Format)",
    "Compare File Explorer & Paint to the Older Version",
    "Windows File Explorer and MS Paint",
    "Windows 10 will support AVIF images format",
    "Display the AVIF Images in Windows 10",
    "Windows 10 AVIF Support Gone?",
  ],
};

export const useAvifInNetlify = {
  readingtime: "6",
  title: "Don't miss out on AVIF when using Netlify",
  description:
    "Learn how to proper configure Netlify so that you can use AVIF image files on your website today.",
  url: "blog/tutorials/use-avif-in-netlify/",
  image: "",
  author: "Justin Schmitz",
  data_published: "25.11.20",
  date_modified: "25.11.20",
  sources: [""],
  tags: [""],
  questions: [""],
};

export const useAvifInWordpress = {
  readingtime: "11",
  title: "How To Use AVIF Images In WordPress",
  description:
    "WordPress doesn't allow uploading AVIF files. Learn how to still use AVIF images on your website today.",
  url: "blog/tutorials/use-avif-in-wordpress",
  image: "",
  author: "Justin Schmitz",
  data_published: "02.12.20",
  date_modified: "02.12.20",
  sources: [
    "blog.shortpixel.com/what-is-avif-and-why-is-it-good",
    "chrisyee.ca/blog/uploading-avif-images-in-wordpress",
    "dev.to/iamrajeev/why-avif-support-in-wordpress-is-important-3g5e",
    "en.wikipedia.org/wiki/Media_type",
    "github.com/wp-media/imagify-plugin/issues/504",
    "libre-software.net/avif-test",
    "premium.wpmudev.org/forums/topic/smush-pro-avif-next-gen-image-format-support",
    "publishing-project.rivendellweb.net/supporting-aadditional-content-types-in-wordpress",
    "wordpress.org/support/topic/consider-adding-avif-support-in-the-future",
    "wordpress.org/support/topic/generating-images-in-avif-format-3",
    "wordpress.org/support/topic/generating-images-in-avif-format-5",
    "wordpress.org/support/topic/will-the-avif-image-format-be-support-in-the-future",
    "wordpress.stackexchange.com/questions/379114/workaround-to-upload-avif-files",
    "wpbeginner.com/glossary/functions-php",
    "wpengine.com/support/mime-types-wordpress/",
  ],
  tags: [
    "image format",
    "wordpress",
    "avif images",
    "file size",
    "mime type",
    "image avif",
    "image optimization",
    "firefox",
    "file format",
    "avif image format",
    "image file",
    "google chrome",
    "faster loading",
  ],
  questions: [
    "Why AVIF Support in WordPress is Important",
    "Why Does a WordPress Site Needs AVIF?",
    "How to Enable AVIF in WordPress?",
    "Is your browser capable of displaying AVIF images?",
    "How to convert images to the AVIF file format",
    "Using the AVIF Next-Generation Image Format on your Sites for Faster Loading Images",
    "Insert AVIF files in WordPress pages or posts",
    "Supporting additional mime types in WordPress",
    "Uploading AVIF images in WordPress",
    "Include support for the AVIF image format",
    "Optimizing your images as a way to speed up your WordPress site",
    "Upload AVIF to WordPress",
  ],
};
